"""Default configuration and command metadata for smartsh."""

DEFAULT_TYPO_MAP = {
    "cdd": "cd",
    "gti": "git",
    "gir": "git",
    "gi": "git",
    "pyhton": "python",
    "pytohn": "python",
    "pnpmn": "pnpm",
    "nmp": "npm",
    "npn": "npm",
    "sl": "ls",
    "lss": "ls",
    "la": "ls -a",
    "mkdr": "mkdir",
    "cd..": "cd ..",
    "grpe": "grep",
    "udate": "update",
    "clera": "clear",
    "exir": "exit",
    "hitory": "history",
    "gtiu": "git",
    "docker-compose": "docker compose",
}

COMMON_COMMANDS = [
    "ls",
    "cd",
    "pwd",
    "mkdir",
    "rm",
    "cp",
    "mv",
    "cat",
    "less",
    "grep",
    "find",
    "awk",
    "sed",
    "chmod",
    "chown",
    "history",
    "clear",
    "exit",
    "git",
    "git status",
    "git add",
    "git commit",
    "git push",
    "git pull",
    "python",
    "python3",
    "pip",
    "pip install",
    "npm",
    "npm install",
    "npm run",
    "pnpm",
    "yarn",
    "docker",
    "docker ps",
    "docker images",
    "docker compose",
    "kubectl",
    "ssh",
    "scp",
    "curl",
    "wget",
    "tar",
    "zip",
    "unzip",
    "htop",
    "top",
    "du",
    "df",
]

DANGEROUS_PREFIXES = [
    "rm -rf /",
    "rm -rf /*",
    "mkfs",
    "dd if=",
    "shutdown",
    "reboot",
    "poweroff",
    "sudo rm",
]

DEFAULT_SENSITIVE_PATTERNS = [
    r"password",
    r"passwd",
    r"token",
    r"secret",
    r"api[_-]?key",
    r"client[_-]?secret",
    r"private\s+key",
    r"-----begin\s+.*private\s+key-----",
]

BUILTINS = {
    "help": "Show smartsh help",
    "smartsh config": "Print config file location",
    "smartsh reload": "Reload command cache",
    "smartsh learning status": "Show personalization status",
    "smartsh learning reset": "Reset learned command history",
}
