"""Default configuration and command metadata for smartsh."""

DEFAULT_TYPO_MAP = {
    "cdd": "cd",
    "gti": "git",
    "gir": "git",
    "gi": "git",
    "pyhton": "python",
    "pytohn": "python",
    "pnpmn": "pnpm",
    "nmp": "npm",
    "npn": "npm",
    "sl": "ls",
    "lss": "ls",
    "la": "ls -a",
    "mkdr": "mkdir",
    "cd..": "cd ..",
    "grpe": "grep",
    "udate": "update",
    "clera": "clear",
    "exir": "exit",
    "hitory": "history",
    "gtiu": "git",
    "docker-compose": "docker compose",
}

COMMON_COMMANDS = [
    "ls",
    "cd",
    "pwd",
    "mkdir",
    "rm",
    "cp",
    "mv",
    "cat",
    "less",
    "grep",
    "find",
    "awk",
    "sed",
    "chmod",
    "chown",
    "history",
    "clear",
    "exit",
    "git",
    "git status",
    "git add",
    "git commit",
    "git push",
    "git pull",
    "python",
    "python3",
    "pip",
    "pip install",
    "npm",
    "npm install",
    "npm run",
    "pnpm",
    "yarn",
    "docker",
    "docker ps",
    "docker images",
    "docker compose",
    "kubectl",
    "ssh",
    "scp",
    "curl",
    "wget",
    "tar",
    "zip",
    "unzip",
    "htop",
    "top",
    "du",
    "df",
]

DANGEROUS_PREFIXES = [
    "rm -rf /",
    "rm -rf /*",
    "mkfs",
    "dd if=",
    "shutdown",
    "reboot",
    "poweroff",
    "sudo rm",
]

DEFAULT_SENSITIVE_PATTERNS = [
    r"password",
    r"passwd",
    r"token",
    r"secret",
    r"api[_-]?key",
    r"client[_-]?secret",
    r"private\s+key",
    r"-----begin\s+.*private\s+key-----",
]

BUILTINS = {
    "help": "Show smartsh help",
    "smartsh config": "Print config file location",
    "smartsh reload": "Reload command cache",
    "smartsh learning status": "Show personalization status",
    "smartsh learning reset": "Reset learned command history",
}

COMMAND_HINTS = {
    "ls": "list files",
    "cd": "change directory",
    "pwd": "show current folder",
    "mkdir": "create directory",
    "rm": "remove files",
    "cp": "copy files",
    "mv": "move or rename",
    "cat": "print file content",
    "less": "view file pages",
    "grep": "search text pattern",
    "find": "find files",
    "awk": "text processing",
    "sed": "stream text edits",
    "chmod": "change permissions",
    "chown": "change owner",
    "history": "show past commands",
    "clear": "clear screen",
    "exit": "exit smart shell",
    "git": "run git command",
    "git status": "show repo status",
    "git add": "stage changes",
    "git commit": "commit staged changes",
    "git push": "push to remote",
    "git pull": "pull from remote",
    "python": "run python",
    "python3": "run python",
    "pip": "manage python packages",
    "pip install": "install package",
    "npm": "run npm command",
    "npm install": "install node packages",
    "npm run": "run npm script",
    "pnpm": "run pnpm command",
    "yarn": "run yarn command",
    "docker": "run docker command",
    "docker ps": "list containers",
    "docker images": "list docker images",
    "docker compose": "run compose command",
    "kubectl": "run kubernetes command",
    "ssh": "open remote shell",
    "scp": "copy over ssh",
    "curl": "send http request",
    "wget": "download from url",
    "tar": "archive files",
    "zip": "create zip archive",
    "unzip": "extract zip archive",
    "htop": "interactive process viewer",
    "top": "show running processes",
    "du": "disk usage",
    "df": "disk free space",
}
